const ERROR_CODES = {
  BAD_REQUEST: 400,
  AUTHORIZATION_ERROR: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  DUPLICATE_EMAIL_EXISTS: 409,
  SERVER_ERROR: 500,
};

const ERROR_MESSAGES = {
  BAD_REQUEST,
  AUTHORIZATION_ERROR,
  FORBIDDEN,
  NOT_FOUND,
  DUPLICATE_EMAIL_EXISTS,
  SERVER_ERROR,
};

module.exports = {
  ERROR_CODES,
  ERROR_MESSAGES,
};
